### PR TITLE
Fixed obsolete hopscotch dependency

### PR DESCRIPTION
**Pull request by whaeck**
Should be obvious what this does ;-)

### CODE REVIEW

**Comment by jlconlin** [comment]
This has to be fixed in `lipservice` first. Wait for a Pull Request there.

**Comment by whaeck** [comment]
lipservice does not appear to need fixing so we can reopen this one.

**Comment by jlconlin** [comment]
This compiled and passed the tests just fine on my machine. Do we need a different version number for this?

**Comment by whaeck** [comment]
Forgot to push the version number yesterday.

**Comment by jlconlin** [comment]
I like the addition of the ReleaseNotes. We need to keep up with this.

**Pull request merged**
