### PR TITLE
Updated to new build system.

### PR DESCRIPTION
**Pull request by nathangibson14**

### CODE REVIEW

**Comment by staleyLANL** [comment]
Are there some summary remarks somewhere of the overarching goal of the changes? I'm not sure I'm seeing it, but maybe I'm looking in the wrong place. I see lots of deleted files (maybe due to simplifications? - if so, a good thing). Also lots of new content that seems to align with "develop", "release", and "unit tests", which basically sounds like those concepts are being made more well-defined. Also a good thing.

**Comment by jlconlin** [comment]
Sorry @staleyLANL We haven't been making many comments on these. We have been updating the build system for all of our repositories and just moved from one to the other. 

The main thing is moving away from [metaconfigure](https://github.com/njoy/metaconfigure). CMake handles dependencies much better---and natively---than metaconfigure did.

**Comment by jlconlin** [comment]
This Pull Request addresses issues: #117, #116, and #115.

**Comment by jlconlin** [comment]
@nathangibson14 I think this is ready for another look.

**Comment by nathangibson14** [comment]
@staleyLANL -- sorry, we should have warned you!  We spent most of the day moving the master branches of all of our repositories over to the FetchContent-based build system.  I think you are already on some version of that for GNDStk, but I'll probably send a PR over on that to clean it up with the latest things I've done.  We can talk more about how this all works if you'd like, plus we're also polishing up some documentation on it.

**Comment by nathangibson14** [comment]
@jlconlin It all works for me, but I didn't see an increment of the version number.  I personally prefer 1.2, but I'll let you make the final call.  And fixing the two broken tests wouldn't be a bad idea :)

**Comment by nathangibson14** [comment]
@jlconlin The tests pass now, or at least will when my lipservice PR is merged into master.  After that happens, release_dependencies will need to be updated.

**Comment by jlconlin** [comment]
I just updated the release dependencies. @nathangibson14 and @whaeck please take a look and let me know if I missed anything.

**Comment by nathangibson14** [comment]
@jlconlin looks good to me.

**Pull request merged**
