### PR TITLE
Removing old tests

### PR DESCRIPTION
**Pull request by jlconlin**
This is the first---of several---Pull Requests for fully integrating modern RECONR into NJOY21. This one includes the main part of RECONR as well as the removal of old tests. These are tests that use old ENDF formats that we no longer support.

### CODE REVIEW

**Comment by jlconlin** [comment]
Sorry, didn't know it was going to be this big!

**Comment by staleyLANL** [comment]
> Sorry, didn't know it was going to be this big!

Look at the bright side. It probably isn't as big as some of the stuff I've foisted on y'all.

**Comment by jlconlin** [comment]
> > Sorry, didn't know it was going to be this big!
> 
> Look at the bright side. It probably isn't as big as some of the stuff I've foisted on y'all.

What comes around, goes around.

**Comment by jlconlin** [comment]
This is no longer needed as it is superseded by #118

**Pull request closed without merging**
