### PR TITLE
no such thing as card 12

### PR DESCRIPTION
**Pull request by apmccartney**

### CODE REVIEW

**Comment by jlconlin** [comment]
We already had a conversation about this. There is such thing as a card 12; the manual has a typo. Yes it is identical to card11, but there is a card 12. Later in the manual it references card 12 separately from card 11.

**Comment by apmccartney** [comment]
That was a change we made (mistakenly)

**Comment by apmccartney** [comment]
That aside there's no reason to specify, test, and store a card that completely redundant to the precious entry.

**Comment by jlconlin** [comment]
There is certainly some ambiguity to this issue as the code and the manual conflict with each other.

**Comment by jlconlin** [comment]
My preciousssssss.

**Comment by apmccartney** [comment]
Let's wait on the travis results on this one

**Comment by jlconlin** [comment]
Let's resolve the conflicts and then this can be merged.

**Pull request merged**
