### PR TITLE
Feature/signature

### PR DESCRIPTION
**Pull request by jlconlin**
This solves #79 and adds the ability to see the "signature" using the `--signature` command line argument.

### CODE REVIEW

**Comment by jlconlin** [comment]
This makes Pull Request 79 obsolete. I will delete it. 

This will officially set the version of NJOY21 to `1.0.0`. Any Pull Request into master after this must increment the version number.

**Comment by jlconlin** [comment]
This also resolves #76.

**Comment by jlconlin** [comment]
This has been updated with the latest version of metaconfigure. Please take a look, review, and maybe (hopefully) approve.

**Comment by whaeck** [comment]
Maybe you should update the test results again following the fix/hbar merge into NJOY2016?

**Comment by jlconlin** [comment]
I forgot to update the tests with the updated NJOY2016. I also need to update the documentation a bit.

**Comment by jlconlin** [comment]
Two of the tests are still failing due to what clang sanitizers call a memory leak. This has been around for a long time (see [this old Travis-CI failure](https://travis-ci.org/njoy/NJOY21/jobs/237353133) from May 2017.)

Note, that I cannot reproduce this memory leak on my Mac using the same CMake invocation made on Linux and the same compilers.

**Comment by jlconlin** [comment]
This addresses #76

**Pull request merged**
